'use client'
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "./_components/Navbar";
import { useStaffStore } from "@/store/staffStore";
import { useEffect } from "react";
import LoadingSpinner from "./_components/LoadingSpinner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { isCheckingStaff, checkStaff } = useStaffStore();
  useEffect(() => {
    checkStaff();
  }, [checkStaff]);

  if (isCheckingStaff) {
    return (
      <LoadingSpinner />
    )
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />

        {children}
        <Toaster />
      </body>
    </html>
  );
}
